# Generated by Django 5.2.1 on 2025-05-26 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FridgeDevice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='冰箱名稱，例如：一樓茶水間冰箱', max_length=100)),
                ('device_id_esp', models.CharField(help_text='ESP32-CAM 的設備 ID', max_length=50, unique=True)),
                ('ip_address', models.GenericIPAddressField(help_text='ESP32-CAM 的 IP 地址')),
                ('port', models.IntegerField(default=81, help_text='ESP32-CAM 的端口號')),
                ('location_description', models.TextField(blank=True, help_text='冰箱位置描述')),
                ('is_active', models.BooleanField(default=True, help_text='設備是否啟用')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': '冰箱設備',
                'verbose_name_plural': '冰箱設備',
            },
        ),
    ]
