# Generated by Django 5.2.1 on 2025-06-03 07:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FridgeDevice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='冰箱名稱，例如：一樓茶水間冰箱', max_length=100)),
                ('device_id_esp', models.CharField(help_text='ESP32-CAM 的設備 ID', max_length=50, unique=True)),
                ('api_url', models.URLField(blank=True, help_text='ESP32-CAM 的完整 API 地址 (例如: http://192.168.1.100:81 或 http://example.com:81)', null=True)),
                ('location_description', models.TextField(blank=True, help_text='冰箱位置描述')),
                ('is_active', models.BooleanField(default=True, help_text='設備是否啟用')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': '冰箱設備',
                'verbose_name_plural': '冰箱設備',
            },
        ),
        migrations.CreateModel(
            name='FridgeOperationLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('operation_type', models.CharField(choices=[('put_in', '放入物品'), ('take_out', '取出物品')], help_text='操作類型', max_length=20)),
                ('operation_start_time', models.DateTimeField(auto_now_add=True, help_text='操作開始時間')),
                ('notes', models.TextField(blank=True, help_text='操作備註')),
                ('fridge_device', models.ForeignKey(help_text='操作的冰箱設備', on_delete=django.db.models.deletion.CASCADE, related_name='operation_logs', to='fridges.fridgedevice')),
            ],
            options={
                'verbose_name': '冰箱操作記錄',
                'verbose_name_plural': '冰箱操作記錄',
                'ordering': ['-operation_start_time'],
            },
        ),
    ]
