# Generated by Django 5.2.1 on 2025-06-03 07:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('fridges', '0001_initial'),
        ('photos', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='fridgeoperationlog',
            name='photo_taken',
            field=models.OneToOneField(blank=True, help_text='本次操作拍攝的照片', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='operation_log', to='photos.photo'),
        ),
        migrations.AddField(
            model_name='fridgeoperationlog',
            name='user',
            field=models.ForeignKey(help_text='執行操作的用戶', on_delete=django.db.models.deletion.CASCADE, related_name='fridge_operations', to=settings.AUTH_USER_MODEL),
        ),
    ]
