# Generated by Django 5.2.1 on 2025-05-26 14:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('fridges', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(help_text='照片文件', upload_to='fridge_photos/%Y/%m/%d/')),
                ('timestamp_esp', models.DateTimeField(help_text='ESP32-CAM 拍攝時間')),
                ('content_type_esp', models.CharField(default='image/jpeg', help_text='照片 MIME 類型', max_length=50)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, help_text='照片上傳到系統的時間')),
                ('recognition_status', models.CharField(choices=[('pending', '等待處理'), ('processing', '處理中'), ('completed', '已完成'), ('failed', '失敗')], default='pending', help_text='LLM 辨識狀態', max_length=20)),
                ('raw_llm_response', models.JSONField(blank=True, help_text='LLM 原始回覆', null=True)),
                ('fridge_device', models.ForeignKey(help_text='拍攝此照片的冰箱設備', on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='fridges.fridgedevice')),
                ('uploaded_by', models.ForeignKey(help_text='觸發拍照的用戶', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploaded_photos', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '冰箱照片',
                'verbose_name_plural': '冰箱照片',
                'ordering': ['-uploaded_at'],
            },
        ),
    ]
