# Generated by Django 5.2.1 on 2025-06-03 07:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('photos', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RecognizedItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='物品名稱', max_length=100)),
                ('quantity', models.CharField(help_text='數量描述', max_length=50)),
                ('estimated_expiry_info', models.TextField(help_text='預估保質期信息')),
                ('placement_date', models.DateField(help_text='放置日期')),
                ('added_at', models.DateTimeField(auto_now_add=True, help_text='物品被記錄到系統的時間')),
                ('notes', models.TextField(blank=True, help_text='附加說明')),
                ('owner', models.ForeignKey(help_text='物品擁有者', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='owned_items', to=settings.AUTH_USER_MODEL)),
                ('photo', models.ForeignKey(help_text='物品來源照片', on_delete=django.db.models.deletion.CASCADE, related_name='recognized_items', to='photos.photo')),
            ],
            options={
                'verbose_name': '辨識物品',
                'verbose_name_plural': '辨識物品',
                'ordering': ['-added_at'],
            },
        ),
    ]
